### ISSUE TITLE
Template not found for name

### ISSUE THREAD

**Issue by mnleles** [joutvhu/spring-dynamic-freemarker#1]
Hello,

After I've upgraded the `spring-boot` to `v2.7.13` I needed to upgrade the `spring-dynamic-jpa` to `v2.7.8` then I needed to change the DynamicQueryTemplates from `new DynamicQueryTemplates()` to `new FreemarkerQueryTemplateProvider()`, however, I started to get the following exception:
```
2023-07-19 10:14:12.562 ERROR [company-service,b2962e701a70a74baec825597217d63e,1c9086cf82a4348c] 8 --- [nio-8080-exec-7] c.j.d.f.FreemarkerQueryTemplateProvider  : freemarker.template.TemplateNotFoundException: Template not found for name "Domain:query.projection".
The name was interpreted by this TemplateLoader: StringTemplateLoader(Map { "Domain:query"=..., "Domain:query.count"=... }).
```

The issue raised because of the following line: [Template template = cfg.getTemplate(name, encoding);](https://github.com/joutvhu/spring-dynamic-freemarker/blob/main/src/main/java/com/joutvhu/dynamic/freemarker/FreemarkerQueryTemplateProvider.java#L45)

It should be:
```
Template template = cfg.getTemplate(name, (Locale) null, (Object) null, encoding, true, true);
```

The last parameter: `boolean ignoreMissing` needs to be `true` to avoid throwing the above exception.

**Comment by joutvhu** [comment]
Fixed in version [v1.0.1](https://github.com/joutvhu/spring-dynamic-freemarker/releases/tag/v1.0.1)
